name: tests
on: 
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:
    inputs:
      enable_debug_tmate:
        required: false
        type: boolean
        default: false

jobs:
  plenary:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Neovim ${{ matrix.nvim_version }} 
      uses: rhysd/action-setup-vim@v1
      with:
        neovim: true
        version: 'stable'

    - name: (debug) Setup tmate session
      if: ${{ (inputs.enable_debug_tmate }}
      uses: mxschmitt/action-tmate@v3

    - name: Test git-prompt-string-lualine
      run: |
        make test

