name: tests
on: 
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:
    inputs:
      enable_debug_tmate:
        required: false
        type: boolean
        default: false

jobs:
  plenary:
    strategy:
      matrix:
        nvim_version: 
          - 'stable'  # v0.9.5
          - 'nightly' 
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install git-prompt-string latest
      run: |
        go install github.com/mikesmithgh/git-prompt-string@latest 
        echo "$HOME/go/bin" >> $GITHUB_PATH

    - name: Setup Neovim ${{ matrix.nvim_version }} 
      uses: rhysd/action-setup-vim@v1
      with:
        neovim: true
        version: ${{ matrix.nvim_version }}

    - name: (debug) Setup tmate session
      if: ${{ inputs.enable_debug_tmate }}
      uses: mxschmitt/action-tmate@v3

    - name: Test git-prompt-string-lualine
      run: |
        make test

